name: CI/CD for Electron App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Install Electron
        run: npm install electron

      - name: Build Electron App for ${{ matrix.os }}
        run: npm run dist

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload Artifacts to GitHub Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/**/*"
          token: ${{ env.GH_TOKEN }}
          tag: ${{ github.ref_name }}
          releaseName: "Release ${{ github.ref_name }}"
          body: "Automated release"
          draft: false
          prerelease: false
